### ISSUE TITLE
Software installation issue

### ISSUE THREAD

**Issue by akshathadixith** [ICAMS/Kanapy#9]
Error message after running any 'kanapy' command: _ModuleNotFoundError: No module named 'kanapy.base'_
Same error when kanapy is installed (following the Readme.md) in both Windows 64-bit operating system and Linux (Ubuntu).

```
(knpy) akshatha@akshatha-VirtualBox:~/Desktop/kanapy$ kanapy -h
Traceback (most recent call last):
  File "/home/akshatha/miniconda3/envs/knpy/bin/kanapy", line 33, in <module>
    sys.exit(load_entry_point('kanapy', 'console_scripts', 'kanapy')())
  File "/home/akshatha/miniconda3/envs/knpy/bin/kanapy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/akshatha/miniconda3/envs/knpy/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/akshatha/miniconda3/envs/knpy/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/akshatha/Desktop/kanapy/src/kanapy/__init__.py", line 6, in <module>
    from kanapy.api import Microstructure
  File "/home/akshatha/Desktop/kanapy/src/kanapy/api.py", line 23, in <module>
    from kanapy.input_output import particleStatGenerator, RVEcreator,\
  File "/home/akshatha/Desktop/kanapy/src/kanapy/input_output.py", line 13, in <module>
    from kanapy.entities import Ellipsoid, Cuboid
  File "/home/akshatha/Desktop/kanapy/src/kanapy/entities.py", line 6, in <module>
    from kanapy.collision_detect_react import collision_routine
  File "/home/akshatha/Desktop/kanapy/src/kanapy/collision_detect_react.py", line 3, in <module>
    import kanapy.base as kbase
ModuleNotFoundError: No module named 'kanapy.base'
```

**Comment by AHartmaier** [comment]
You need a C++ compiler, e.g. g++, and make to get a proper installation with
$ pip install -e .
Alternatively, you may try to create the base-libary with the commands:
$ cmake CMakeLists.txt
$ make
